---
title: "Resumen Teorico - Algebra 1"
author: "Ezequiel Remus"
date: "21 de Agosto de 2021"
output:
  html_document:
    df_print: paged
    toc: yes
  html_notebook:
    theme: paper
    toc: yes
    toc_float: yes
subtitle: "Trabajos Practicos - Laboratorio de Datos"
---

# Conjuntos

> **Definición (Informal)** : Un conjunto es una coleccion de objetos, que llamaremos 
> $elementos$, que tiene la propiedad que dado un objeto cualquiera, se puede decir 
> si ese objeto es un elemento del conjunto o no. (Idea de pertenencia)

Debemos tener en cuenta que el orden de los elementos dentro de un conjunto no importa, además, un conjunto no tiene en cuenta repeticiones.

*Pertenencia:*
  
  - Ejemplo
  
 1. $A = \{ 1,2,3\} \Rightarrow 1 \in A, \hspace{0.2cm} 2 \in A , \hspace{0.2cm} pero  \hspace{0.2cm} 4 \notin A , \hspace{0.2cm} tampoco  \hspace{0.2cm}\varnothing \notin A$

 2. $B = \{ 2, \{1\}, \{2,3\}\} \Rightarrow \{1\} \in B, \{2,3\} \in B, \hspace{0.2cm} pero \hspace{0.2cm} 3 \notin B, \hspace{0.2cm} tampoco  \hspace{0.2cm} 3 \notin B$ 

> **Definición (Subconjuntos e Inclusión)** :
> Dado un conjnto $A$. Se dice que otro conjunto $B$ $\textit{está contenido}$  
> en $A$, $B \subseteq A$, si todo elemento de $B$ es un elemento de $A$. En este 
> caso $B$ es un subconjunto de $A$. Luego, como es obvio, si no esta contenido se
> se nota $B \nsubseteq A$

Observemos que, para que dos conjuntos sean iguales, uno debe estar siempre contenido en el otro, por lo que:
$$A = B \Leftrightarrow A \subseteq B \hspace{0.2cm} y \hspace{0.2cm} B \subseteq A$$

> **Definición (Conjunto de Partes)** :
> Dado un cunjunto $A$. El *conjunto de partes* de $A$, que se nota $\mathcal{P}(A)$
> es el conjunto formado por todos los subconjuntos posibles de $A$.
> $$ \mathcal{P}(A) = \{ B: B \subseteq A\} \hspace{0.4cm} \lor \hspace{0.4cm} B \in \mathcal{P}(A) \Leftrightarrow  B \subseteq A$$

## Operaciones entre conjuntos

Dado un conjunto referencial $U$, donde los conjuntos $A,B,C$ forman parte (estan contenidos en $U$), definimos:

> **Complemento:** $A^c = A' = \{x \in U : x \notin A\}$

> **Unión:** $A \cup B = \{ x \in U : x \in A \hspace{0.2cm} \lor \hspace{0.2cm} x \in B\}$

> **Intersección:** $A \cap B = \{x \in U : x \in A \hspace{0.2cm} \land \hspace{0.2cm} x \in B\}\}$

> **Leyes de De Morgan:**
>
>> $(A \cup B)^c = A^c \cap B^c$
>>
>> $(A \cap B)^c = A^c \cup B^c$

> **Leyes Distributivas**
>
>> $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$
>>
>> $A \cup (B \cap C) = (A \cup B) \cap (A \cup C)$

> **Diferencia:**  $A - B = A \cap B^c$, lo cual es equivalente a
>
> $x \in A  \hspace{0.2cm} \land \hspace{0.2cm} x \in B \Leftrightarrow x \in A \hspace{0.2cm} \land \hspace{0.2cm} x \notin B$
>
> Es decir, es el conjunto de los elementos de $A$ que no estan en $B$

> **Diferencia Simetrica:** $A \vartriangle B = \{ x \in U : (x \in A \hspace{0.2cm} \land \hspace{0.2cm} x \notin B) \hspace{0.2cm} \lor \hspace{0.2cm} (x \in A \hspace{0.2cm} \land \hspace{0.2cm} x \notin B)\}$
>
> Donde tambien son equivalentes las siguientes igualdades
>
> $A \vartriangle B = (A-B) \cup (B-A) = (A \cap B^c) \cup (B \cap A^c) = (A \cup B) - (A \cap B)$
>
> Es decir, son los elementos que estan o bien en uno o en el otro pero que no estan en la interseccion

## Tablas de verdad

Acá vamos a hacerla sencilla. Sabmos operar con vectores en `R` y con valores Boleanos.
Por lo que solo definiremos a que son equivalentes logicos de la unión, intersección, etc. 
Y luego, simplemente armaremos un pequeño script que nos diga los valores.

- El *Complemento* se corresponde con la negación.
- La *Unión* se corresponde con el `or`, es decir el "o no excluyente. 
- La *Intersección* se corresponde con el `and`
- La *Diferencia Simetrica* se corresponde con en `xor`
- La *Inclución* se corresponde con la contención de un conjunto en otro.
- La *Igualdad* se corresponde con el si y solo si.

Hagamos una pequeña tabla de verdad en `R`

```{r}
V <- TRUE
F <- FALSE

A <- c(V,V,F,F)
B <- c(V,F,V,F)

cat("Siendo A:" , A, "\n")
cat("Siendo B:" , B, "\n")
cat("Se tiene que:", "\n")
cat("A complemento B: ", A != B, "\n")
cat("A unión B: ", A | B, "\n")
cat("A intersección B: ", A & B, "\n")
cat("A Dif. Simetrica B: ", xor(A,B), "\n")
cat("A Igualdad B: ", A == B, "\n")
```
Quizas despues pueda mejorar un poquito la estetica de esto, por alguna razón separa todos los `cat` en varios bloques por mas que este en uno...

## Producto Cartesiano

> **Definicion: (Prod. cartesiano)** Dados dos conjuntos $A, B$. El producto cartesiano de $A$ con $B$, el cual se nota $A \times B$, es el conjunto de los pares ordenados.
> $$A \times B = \{ (x,y) : x \in A \hspace{0.2cm} \land \hspace{0.2cm} y \in B\}$$

Su representacion es en el plano de coordenadas.

# Relaciones

> **Definición:**(Relación)
> Dados dos conjuntos $A$ y $B$. Una relación $\mathcal{R}$ de $A$ en $B$ es
> un subconjunto cualquiera $\mathcal{R}$ del producto cartesiano $A \times B$.
> Es decir, $\mathcal{R}$ es una relación de $A$ en $B$ si $\mathcal{R} \in \mathcal{P}(A \times B)$


